export const GET_CHARACTERS = 'GET_CHARACTERS';
export const CHARACTER_DETAIL = 'CHARACTER_DETAIL';
export const CLEAN_DETAIL = 'CLEAN_DETAIL';

export const ADD_FAVORITES_CHARACTER = 'ADD_FAVORITES_CHARACTER';
export const DELETE_FAVORITES_CHARACTER = 'DELETE_FAVORITES_CHARACTER';
export const FILTER = 'FILTER';
export const ORDER = 'ORDER';
